### ISSUE TITLE
111 different errors while attempting to build app in Xcode

### ISSUE THREAD

**Issue by Casuallynoted** [swiftcodex/Swift-Radio-Pro#23]
Lots of errors about commands that have been renamed, along with errors from the different libraries used. I can't seem to build it at all.

**Comment by Jxrgxn** [comment]
Guess it's time for an update then.

**Comment by swiftcodex** [comment]
@Casuallynoted are you using an Xcode beta?

**Comment by Casuallynoted** [comment]
@swiftcodex I've opened it in both Xcode 7.3 and the Xcode 8 Beta, but it doesn't seem to change anything

**Comment by swiftcodex** [comment]
@Casuallynoted on a clean clone, I'm not getting any errors in Xcode 7.3.1. 🤔
@Jxrgxn are you getting any errors in the stable version of Xcode?

**Comment by Casuallynoted** [comment]
Whoops! Looks like the version I first opened with Xcode 8 is what's giving me errors in Xcode 7.3, a clean clone works great! Sorry about that!

**Comment by swiftcodex** [comment]
@Casuallynoted awesome! Yeah, I need to get on an Xcode 8 branch sooner than later...

**Comment by Casuallynoted** [comment]
It's all good, thank you so much for being willing to look into it, the app looks awesome! :)
