### ISSUE TITLE
Reject by Apple:  We discovered one or more bugs in your app when reviewed on iPhone running iOS 9.3.2 on Wi-Fi

### ISSUE THREAD

**Issue by hungwei0331** [swiftcodex/Swift-Radio-Pro#24]
Excuse me, after submission, they reject by this reason,

We discovered one or more bugs in your app 

when reviewed on iPhone running iOS 9.3.2 on Wi-Fi(ipv6 network),

but i had test it, it works well,

I am wondering which part should I fix, thank in advance for reply

**Comment by Jxrgxn** [comment]
Is that all they gave you? If so I'd fork the repo and see what's up since
we haven't updated in a while.

**Comment by hungwei0331** [comment]
the detail as below:

From Apple
2. - 1 PERFORMANCE: APP COMPLETENESS
Performance - 2.1


We discovered one or more bugs in your app when reviewed on iPhone running iOS 9.3.2 on Wi-Fi.

Specifically, no audio was present when playing any station and the stations kept loading.

We've attached screenshot(s) for your reference. 

Next Steps

Please run your app on a device to identify the issue(s), then revise and resubmit your app for review.

Apps are reviewed on an IPv6 network. Please ensure that your app supports IPv6 networks, as IPv6 compatibility is required.

For additional information about supporting IPv6 Networks, please refer to Supporting IPv6 DNS64/NAT64 Networks and Supporting IPv6-only Networks.

For a networking overview, see About Networking.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue(s). For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue(s).

Resources 

If you have difficulty reproducing a reported issue, please try testing the workflow described in Technical Q&A QA1764: How to reproduce bugs reported against App Store submissions.

If you have code-level questions after utilizing the above resources, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log

**Comment by Jxrgxn** [comment]
Cool. So it's a networking issue. You need to test it on an IPv6 network...
So why can't you do it?
ᐧ

**Comment by hungwei0331** [comment]
i had test it on IPv6 network,
but it works well, so i dont know waht is the reason ..

**Comment by hungwei0331** [comment]
sorry, i had test it on IPv6 again to make sure,
it really doest work

**Comment by swiftcodex** [comment]
"we haven't updated in a while." While @Jxrgxn has been busy, this project is maintained by myself and I push updates routinely. @hungwei0331 - thanks for asking, this is not an error with the radio app code. The error is typically in the way you handle radio stations (make sure you don't hard code IP addresses, etc) and is beyond the scope of an issue for this code. We can offer no free support in helping you with your networking code. If you are new to iOS development, please find someone in your area who can help you or, we offer paid consulting as well. Good luck!
