### ISSUE TITLE
bluetooth doesn't work

### ISSUE THREAD

**Issue by syuemingfang** [swiftcodex/Swift-Radio-Pro#25]
I saw the recently commit it support bluetooth,
after I tested it doesnt work.

**Comment by swiftcodex** [comment]
Hi @syuemingfang, could you please give me a little bit more information... Are you having trouble with streaming to bluetooth speakers, streaming to a car via bluetooth, or is there a specific device that is giving you trouble? Thanks!

**Comment by syuemingfang** [comment]
After I connected bluetooth speaker and bluetooth headphone,
the music still play on default iphone speaker,
then I change play music by Apple music app,
it can play by default speaker.

**Comment by swiftcodex** [comment]
Thanks for the extra details -- I will look into it this weekend!

**Comment by swiftcodex** [comment]
Hi @syuemingfang, I just tested a clean clone of the code with bluetooth speakers and an iPhone 6+. It is working great for me with Bluetooth 4 speakers. Are you using the master branch?

**Comment by swiftcodex** [comment]
Additionally, if you have recently used another bluetooth app: Try closing that app and turning the bluetooth speakers off and on and bluetooth off and on in your General Settings in the iPhone. Then relaunching the app.

**Comment by swiftcodex** [comment]
I'm marking this issue as closed as 
(1) the master branch is working with bluetooth v4 speakers upon testing 
(2) Two apps in the app store based on this code are working with bluetooth speakers

**Comment by swiftcodex** [comment]
@syuemingfang - the commits this morning improve bluetooth support!

**Comment by syuemingfang** [comment]
it works well now, thank you so much
