### ISSUE TITLE
Convert to AVFoundation?

### ISSUE THREAD

**Issue by Jxrgxn** [swiftcodex/Swift-Radio-Pro#31]
I was told by a reliable source to switch over to AVPlayer/

**Comment by swiftcodex** [comment]
Are you referring to the depreciation of MPMoviePlayer in iOS 10? There is already an AVPlayer branch of this project. 🔊  If you would like to be a contributor, here is a direct link: https://github.com/swiftcodex/Swift-Radio-Pro/tree/avplayer

**Comment by swiftcodex** [comment]
There's now an Xcode 8 branch that uses AVPlayer: https://github.com/swiftcodex/Swift-Radio-Pro/tree/xcode8

**Comment by swiftcodex** [comment]
Update 12/26/2016: There has been some major progress made on the AVPlayer branch thanks to @giacmarangoni! 

The default AVPlayer/Swift 3 branch is now: https://github.com/swiftcodex/Swift-Radio-Pro/tree/xcode8 

I would encourage everyone interested in AVPlayer to start with that branch.

**Comment by adinertia** [comment]
Hello,

Any ideas why remoteControlReceived not working on AVPlayer branch.

Thanks
