### ISSUE TITLE
It is not compatible with xcode 8

### ISSUE THREAD

**Issue by Elicast** [swiftcodex/Swift-Radio-Pro#36]
is scheduled for an update compatible with xcode 8, I am not able to convert

**Comment by swiftcodex** [comment]
Hi @Elicast, are you using the latest code from the master branch? You should not have to convert as it has already been graciously converted by @fethica. 

I just tested a clean clone of the master branch with Xcode 8.1 / Sierra 10.12.1 and it compiles with no errors. No modifications required.

**Comment by Elicast** [comment]
I am using the radio single version.
when I open calls to convert to Syntactic 3.2
then I do the conversion sitax, aparace several errors when you are using Excode 8.1 and convert see the mistakes I'm referring to.

multi correct version works but the single version does not work anymore

**Comment by swiftcodex** [comment]
@Elicast - The radio single version will not be upgraded. It is to be used as an example of what to remove, code wise. It was made in about 10 minutes by simply removing code. You can use the latest build as a starting point. If you can not figure it out on your own, I'd suggest finding a developer in your area or use a developer on fiverr (or some other low-cost outsourcing site). Good luck.
