### ISSUE TITLE
Master branch asking for conversion to Swift 3

### ISSUE THREAD

**Issue by RajChanchal** [swiftcodex/Swift-Radio-Pro#37]
Seems like Master is not Swift 3 converted. Here is the screenshot.
<img width="842" alt="screen shot 2016-11-18 at 5 22 10 pm" src="https://cloud.githubusercontent.com/assets/7058465/20431495/afcf238c-adb3-11e6-9c69-3c4d729e8a73.png">

**Comment by swiftcodex** [comment]
Hi, sorry you are having trouble. What version of Xcode are you using? Did you make a clean clone? i.e. Download the latest master code into a different directory?

**Comment by swiftcodex** [comment]
Quick Test: I just downloaded the master code and ran it. No conversion required w/ Xcode 8.1. 

![screen shot 2016-11-18 at 7 57 59 am](https://cloud.githubusercontent.com/assets/2042313/20434388/c99bab54-ad64-11e6-8bc5-96d5eac78737.png)

**Comment by RajChanchal** [comment]
It is weird, I do also have Xcode 8.1 and tried re-cloning again in another directory too.
<img width="913" alt="screen shot 2016-11-18 at 7 24 37 pm" src="https://cloud.githubusercontent.com/assets/7058465/20435217/b63edc74-adc4-11e6-8c13-0b3b044b0215.png">

**Comment by swiftcodex** [comment]
Are you sure you're cloning the master branch? The other branches are not in Swift 3.

**Comment by swiftcodex** [comment]
To ensure that it is not a problem with the way you are cloning, try downloading the master branch. 
![screen shot 2016-11-18 at 8 33 34 am](https://cloud.githubusercontent.com/assets/2042313/20435580/e4067122-ad69-11e6-989c-bf9c88d46a1c.png)

**Comment by easyjam** [comment]
If you're using Xcode 8 beta and still have Xcode 7 installed you will have this problem. You need have Xcode 8 only on your system.

**Comment by NKaufmann** [comment]
Got the same problem using Xcode 8.1 and a fresh clone.

**Comment by swiftcodex** [comment]
I'll leave this open. Though, this appears to be an Xcode system configuration problem with your machines, unrelated to the code. If anyone has more advice for these folks, feel free to post.

**Comment by bugsFixed** [comment]
I meet the same problem, Xcode 8.1

**Comment by RealBug** [comment]
Hello all,

the main target is in swift 3. The popup that you see is for the test's target. You can easily pass it to Swift 3 with the automatic Apple migrator. I send a PR for it :)

**Comment by swiftcodex** [comment]
@RealBug - Thanks for the clarification and the PR. It is appreciated!

**Comment by RealBug** [comment]
U're welcome. You did a nice open source app :)

**Comment by swiftcodex** [comment]
@RajChanchal if RealBug's suggestion is satisfactory to you, could you please close this Issue? Also, you may want to pull the latest master w/ RealBug's code. Thank you,

**Comment by RajChanchal** [comment]
Thanks @RealBug  and @swiftcodex , yes I would really like to pull the PR.
