### ISSUE TITLE
skip stationlist on start

### ISSUE THREAD

**Issue by Babom** [swiftcodex/Swift-Radio-Pro#38]
hi is this possible to play station on start ?

**Comment by swiftcodex** [comment]
yes. you can do that with two lines of code.

**Comment by Babom** [comment]
thanks for answer, but How do I do that exactly please

**Comment by swiftcodex** [comment]
How do you set a variable and perform a segue? You should learn that your first week of iOS development. I'd highly recommend you take a free online class, buy a book, or find a developer in your area who can help. This forum is not here to teach basic programming. Good luck!

**Comment by Babom** [comment]
ok thank you

**Comment by swiftcodex** [comment]
hint... set the selected station variable and perform a segue in the stations controller load.
Or, modify the code to be a single station (there's an example here: https://github.com/swiftcodex/Swift-Radio-Pro/tree/single-station)

**Comment by Babom** [comment]
super, thank you much
