### ISSUE TITLE
app rejected by apple ipv6

### ISSUE THREAD

**Issue by Babom** [swiftcodex/Swift-Radio-Pro#41]
hi is the code support ipv6 ?

`Performance - 2.1
We discovered one or more bugs in your app when reviewed on an iPhone running iOS 10.1.1 on Wi-Fi connected to an IPv6 network.

Specifically, we noticed no audible content played within the app although the controllers state it is “Playing.” We've attached a screenshot for your reference.
`

**Comment by swiftcodex** [comment]
Yes. There are over 80 apps in the app store using this code.

Do you understand what it ipv6 network support requires? i.e. You cannot use IP addresses for station streams, etc

**Comment by Babom** [comment]
ok i understand yet thank you

**Comment by swiftcodex** [comment]
Regarding ipv6 support, the most common reason for rejection is using a stream url such as "http://55.23.55.120", instead you must use something like "http://mystream.com/rock" etc
