### ISSUE TITLE
Use project for Android

### ISSUE THREAD

**Issue by RBrenet** [swiftcodex/Swift-Radio-Pro#42]
Hello, first thank you very much, your project is Amazing. It's work very well and it's really a clean and professionnal project on iOS.
I ask you if you know something or tools to convert for Android ? Because I am not Good with Java.

Thanks. Romain

**Comment by swiftcodex** [comment]
Does anyone know of any Android open-source radio projects they could recommend for this person?

**Comment by xabispacebiker** [comment]
Android-Open-Radio is a nice option: https://github.com/malah-code/Android-Open-Radio

**Comment by xabispacebiker** [comment]
I have developed an android version. It's just 1.0 so feel free to contribute. https://github.com/estekadigital/arrosapp
