### ISSUE TITLE
No Metadata available. How to feed-in track info anyway?

### ISSUE THREAD

**Issue by donlent** [swiftcodex/Swift-Radio-Pro#43]
Dear Matthew, Dear all

Maybe somebody of you has a good idea. Unfortunately the radio stations that I want to use don't include metadata about the broadcasted songs. :-( However I was able to find that they parse another JSON file available on the internet where the track information is stored.

Is there an easy way to somehow "override" the metadata check in the project and use another JSON file stored in the web?

I'm abviously not asking for a "ready to go" solution.... But since I'm not an expert programmer wanted to ask for some useful hints on how to ideally achieve such a thing. Thanks a lot for your help! Any comments are much appreciated!

All the best,
Don

**Comment by swiftcodex** [comment]
I would look into the things people do with the Echo Nest API. You can absolutely override the metadata check and make a call to another api.

**Comment by swiftcodex** [comment]
Another solution would be to contact the radio stations. Usually, their streaming solution should allow meta-data to be added. You typically need their permission (depending on a number of factors) to use their radio station in your app, so, you'll need to contact them anyways. And, most radio stations will want a good user experience for app listening...

**Comment by donlent** [comment]
Hi Matthew!
Thank you very much for the quick reply. I will definitely check what you suggested. Will keep you posted on the progress so that maybe you could integrate it into your app.

Best regards,
Don

**Comment by swiftcodex** [comment]
@donlent - We charge $225/hr for custom work. Feel free to get in touch here: http://matthewfecher.com/contact

**Comment by swiftcodex** [comment]
@donlent - We keep this code pretty light and nimble, so that others can easily modify. I have tested the code with Echo Nest, and it works great. However, we will probably not implement it into master.

**Comment by swiftcodex** [comment]
@donlent - Some of the things we have built into this code for clients includes: Facebook login, Profiles, Saving Favorite Tracks, Playlists, Genres, Tempo Analyzing, etc. So, there's almost unlimited things you can use this as a starting place for.
