### ISSUE TITLE
Track Info not shown on external screen when USB connected

### ISSUE THREAD

**Issue by donlent** [swiftcodex/Swift-Radio-Pro#44]
Hi all!

Just discovered a little issue:

When you stream via Bluetooth everything works as expected:
The track & artist info are displayed to the system where you're streaming to (for example car navigation)

However when playing back via USB then no track info is transmitted.

Other radio / media player apps do that for example Spotify. Even the album cover is transmitted (note: only via USB supported because of Bluetooth AVRCP 1.4 on Apple devices. For album cover via Bluetooth AVRCP 1.6 would be needed...)

Is that "by design" right now (not yet implemented) or is it a bug? :-P

Best regards,
Don

**Comment by swiftcodex** [comment]
No plans to add that feature, anyone is welcome to do it! PRs are accepted
