### ISSUE TITLE
Thanks to everyone for an amazing 2016!

### ISSUE THREAD

**Issue by swiftcodex** [swiftcodex/Swift-Radio-Pro#48]
Hey everyone!
They say "build it, and they will come". However, as you all know, that is not always the case with open-source projects. This project started as a fun little excuse for me to practice and learn Swift (coming from Obj-C). It would have probably just stayed on my hard drive, if it were not for @Jxrgxn's encouragement to make it public on Github. 

Fast forward to a little over a year later, and it's been starred over 1,500+ times, 300+ branches, and there are over 80+ apps in the app store (that I know about). Most of the apps are in foreign (non-USA) app stores. 

I'd like to extend a gracious and heartfelt thanks to everyone who contributed!

Your contributions are directly responsible for dozens of apps being created and distributed across the world (that may have otherwise never seen the light of day). At least two people have emailed me that they received jobs because of this code. So, you're also helping people earn a livelihood and improving the world a little at a time, through code.

I wanted to publicly THANK all the awesome people who contributed (alphabetical order by username):

@eaconner 
@fethica 
@giacmarangoni
@Jonahss 
@Jxrgxn 
@naoyashiga 
@phatblat 
@rajabishek 
@RealBug 
@SuperChloe 
@WadeSellers 

Also, big thanks to everyone who used the code, and helped others with the project!

**Comment by fethica** [comment]
Hey @swiftcodex !

Special THANKS goes to you for making this possible and giving us the opportunity to contribute and learn from this amazing project 😊

**Comment by eradiodj** [comment]
I am looking for a developer to assist me with customizing this code for my radio station. If anyone is available or interested in a small paid gig please PM me.

**Comment by iDevelopper** [comment]
What is wrong with this code? What is your radio station url?

**Comment by eradiodj** [comment]
I am not currently using the code, just looking for a developer to help me implement it for my station. I know zero about Swift and programming.

**Comment by iDevelopper** [comment]
Ok understood, what is your station url?

**Comment by eradiodj** [comment]
PureRock.US

**Comment by kryptics** [comment]
Hey Eradiodj

Drop me a note, I can't figure out how to PM on GitHub, I can def help you... Losgranos@gmail.com

**Comment by Javame** [comment]
Hey Matthew,

You are one truly a great guy for released the code to Git Hub and I use it
everyday to customize base on my project need,   I also would like to
thanks everyone who help contribute to the project as well.

I have learn more about Swift programming and continue to help improved
with the project.


Thank you all,
Char

**Comment by eradiodj** [comment]
Hey kryptics,
Email sent.
Thanks

**Comment by swiftcodex** [comment]
Hey @Javame thanks! I wish I had more time to maintain the project. These days, other people are stepping up to improve the project. I am truly grateful to everyone who is upgrading and maintaining the projects so it can benefit future developers. Thanks all!
