### ISSUE TITLE
App Rejected

### ISSUE THREAD

**Issue by sanbroz** [swiftcodex/Swift-Radio-Pro#49]
I got a message from Apple after submitting App for approval-

_We discovered one or more bugs in your app when reviewed on iPad running iOS 10.2.1 on Wi-Fi connected to an IPv6 network.

Specifically, radio did not play any audible content._

It this issue related to Swift-Radio-Pro code or something else?

**Comment by swiftcodex** [comment]
Probably your radio stream, as there are over 80 apps in the app store using this code in the past 6 months. One thing to check is to make sure your code is compliant with IPv6 networks- For example, No IP addresses for radio stations. Apple will reject a stream like http://44.33.22.44 but http://shoutcast/rock123 is okay
