### ISSUE TITLE
You may have inadvertently included your secret API

### ISSUE THREAD

**Issue by edglazer** [swiftcodex/Swift-Radio-Pro#5]
Just started poking around with this, and it looks like your Last.fm api key and secret might have been left in the code?

**Comment by swiftcodex** [comment]
Yes, people may use it for testing. However, I ask that they change it before submitting to the app store. (Plus, it would be self-defeating for someone to submit it to the app store with the testing keys, as it would quickly throttle out and their album art downloads would stop working.)
