### ISSUE TITLE
AppleAir play xcode 8.1

### ISSUE THREAD

**Issue by RBrenet** [swiftcodex/Swift-Radio-Pro#50]
Hello, did you plan to implement AirPlay in the project? It would be really fantastic. If not, will you convert the single radio project to swift 3 xcode 8.1? thank you very much

**Comment by kryptics** [comment]
Oh good I thought the single radio was going not broken to me...

**Comment by swiftcodex** [comment]
The Single Radio Branch is just a simple example of what to remove. It can be made in about 5 minutes. It would be ineffective to make one everytime master is updated.

**Comment by kryptics** [comment]
Ooooh that makes sense great thanks Mathew

**Comment by RBrenet** [comment]
Ok thanks no problem.

And a button with airplay it's possible ? :-)

**Comment by RBrenet** [comment]
I begin read documentation in apple :-)

**Comment by swiftcodex** [comment]
@RBrenet if you want to add AirPlay and share wit with the repo, I would look forward to that pull request. My current open-source efforts are focused on the new AudioKit Synthesizer and have no plans to add that feature here myself. Thanks!
