### ISSUE TITLE
The app is perfect but is missing one big thing:!

### ISSUE THREAD

**Issue by brotherss** [swiftcodex/Swift-Radio-Pro#52]
Hello, can you add option for favourite stations, its perfect app but favourite stations is something primary. Please it will be great to have favourite option. Regards

**Comment by swiftcodex** [comment]
As per the readme, we have added favorite stations for clients to this app many times. You can do it yourself, or hire us or someone else to quickly do it for you. The base code stays lean so it can be customized!

**Comment by brotherss** [comment]
Hi, you said that you can do it. How much will cost and how long will take? Thanks

**Comment by swiftcodex** [comment]
About 1 hour if you just wanted something simple. If you wanted with user logins to store the favoritees, it would be much more complex and require a backend system on the web. Our typical rate is $200/hr

**Comment by brotherss** [comment]
Hi. I just need on the app to have option that users will add stations to favorites. Can you do just this I need and how much will cost.?

**Comment by swiftcodex** [comment]
We typically have a $500 minimum for any work. Though, this is very easy. It could be turned around in less than a day. If that is too much, you may just want to have someone on Upwork.com do it for $50-100.
