### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Gharveys** [swiftcodex/Swift-Radio-Pro#56]
Hello, give me these errors when compiling the application from products -> Archive

Check dependencies

Failed to create provisioning profile. There are no devices registered in your account on the developer website. Plug in and select a device to have Xcode register it.

No profiles for 'XXX' were found:  Xcode couldn't find a provisioning profile matching 'XXX'.

Code signing is required for product type 'Application' in SDK 'iOS 10.3'

What is the problem?

**Comment by kryptics** [comment]
You probably need to set up a new provision profile, that shud fix it

**Comment by iDevelopper** [comment]
You need to register your device for development.

**Comment by Gharveys** [comment]
How would I have to do this? I have some knowledge about xcode, but it is the first time I use an open source code like this, if you could tell me what I should do, help me monton, a hug! excuse my English.

**Comment by kryptics** [comment]
You need a developer account, if you dont have one you need to get one first...

**Comment by Gharveys** [comment]
@kryptics How do I do that?

**Comment by kryptics** [comment]
https://developer.apple.com/

it's $100 per year

**Comment by kryptics** [comment]
https://developer.apple.com/programs/

**Comment by swiftcodex** [comment]
@kryptics @iDevelopper Thanks for helping out with the questions here- I've been slammed and I really appreciate you helping other devs questions about the code!

**Comment by kryptics** [comment]
no prb - i know how it feels to be completely lost... heheh

**Comment by Gharveys** [comment]
Thank you all for the answers!

**Comment by iDevelopper** [comment]
You don't need to buy the program developper to test on your device.

**Comment by kryptics** [comment]
I stand corrected you are right Patrick...
