### ISSUE TITLE
UICollection View Version

### ISSUE THREAD

**Issue by alucard875** [swiftcodex/Swift-Radio-Pro#58]
please can someone provide a uicollectionView version for this project instead of table view
Thanks a lot

**Comment by swiftcodex** [comment]
Asking someone to do basic programming 101 for you is an inappropriate use of an issue

**Comment by alucard875** [comment]
Sorry i didn’t know

**Comment by swiftcodex** [comment]
if you do not feel like reading a book and or watching a tutorial on how to use UICollectionView, you are welcome to hire any of the contributors to help you. Though, you may surprise yourself, if you have any Swift experience you should be able to learn UICollectionViews and create a version the same day.... the concepts are very similar. Good luck!

**Comment by alucard875** [comment]
thank you for your reply i’ll do my best before asking someone
:)
