### ISSUE TITLE
Bug on network down

### ISSUE THREAD

**Issue by bartollo** [swiftcodex/Swift-Radio-Pro#61]
I noticed that when I run the radio and lose the connection, the audio session does not come back ... I made an update in the code using reacheability, I would like to know if I have the possibility to be a collaborator of the project or just show the code for you. Thank you!

**Comment by swiftcodex** [comment]
Hello @bartollo- anyone can make a pull request. Thank you!

**Comment by bartollo** [comment]
Hello @swiftcodex , I will do the pull request ... thanks!

**Comment by sdvigov** [comment]
hello) i try to convert Swift4 and no work)
i leave Swift3 but no work JSON ) 
oh and ah Use the Xcode9

**Comment by fethica** [comment]
@sdvigov you can check the xcode 9 branch : https://github.com/swiftcodex/Swift-Radio-Pro/tree/xcode9
