### ISSUE TITLE
 Cyrillic symbols in track names

### ISSUE THREAD

**Issue by vfmradio** [swiftcodex/Swift-Radio-Pro#63]
Hello! In the names of tracks there are Cyrillic symbols, they are not displayed normally, is it possible to fix it?

**Comment by RomainDev25** [comment]
Hello, do you have put meta utf-8 in your index.html file ?

`<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`

**Comment by vfmradio** [comment]
They are displayed correctly on the Icecast page, but not in the application.

**Comment by RomainDev25** [comment]
Yes in Icecast page, but do you have this meta in you html file in www folder, in your app ?

**Comment by RomainDev25** [comment]
And encoding of your file is correct ? UTF8 without bom ?

**Comment by vfmradio** [comment]
I do not understand you. I thought that I need to specify the encoding in the metadataUpdated method in the NowPlayingViewController module.

**Comment by RomainDev25** [comment]
Ok, in your cordova application, you have a folder www with index.html, and other html.
Check if you have meta <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> in your file.
I have this problem with accent.

**Comment by vfmradio** [comment]
RomainDev25, я имел в виду приложение Swift-Radio-Pro)

**Comment by RomainDev25** [comment]
Can you put your resolution for others ?

Have a nice day.

**Comment by vfmradio** [comment]
This problem is solved here https://github.com/giacmarangoni/Swift-Radio-Pro/commit/9ea267109971f096aaa4cdfd9ddb7dccc9eeefc9

**Comment by vfmradio** [comment]
In ios11, when the track name in Cyrillic appears, the application drops. In this case, ios10 worked. Can you help? To display the name of the track in Cyrillic I used giacmarangoni/Swift-Radio-Pro@9ea2671

**Comment by vfmradio** [comment]
Problem solved! If you do not use these fixes, the Cyrillic is displayed correctly! But only on devices with ios11 and higher

**Comment by swiftcodex** [comment]
I wonder if we should add this upgrade to the main repo?

**Comment by vfmradio** [comment]
Now the code from the main branch works fine without these changes, in ios11 for sure! They were needed in earlier versions of ios.

**Comment by swiftcodex** [comment]
Okay, great. I'm going to close this issue. Thank you.
