### ISSUE TITLE
OneSignal Notifications Coded in, possible?

### ISSUE THREAD

**Issue by kryptics** [swiftcodex/Swift-Radio-Pro#74]
Hey, Peeps @fethica @swiftcodex @joemcmahon

I was wondering if it's possible to code in OneSignal notifications properties to the master fork, I actually managed to add it to the code manually, but I think it might be better if it's added as part of the master... just a thought (...plus its a free service)

-krs

**Comment by joemcmahon** [comment]
I'll defer to @fethica and @swiftcodex on whether it's appropriate for the project; if they say yes, and you need help making a pull request, let me know and we can work on it offline.

**Comment by fethica** [comment]
Hey @kryptics, thanks for the interesting idea!

I leave it to @swiftcodex to make the call, for me I think we should keep the project lightweight, simple and easy to customize, based on Apple's native frameworks, so it's easy for us to maintain.

**Comment by swiftcodex** [comment]
That's a great idea @kryptics. However, there are so many Push notification services. Many developers would have to search out and remove that code to add the one they use. Probably best to leave it out.

**Comment by kryptics** [comment]
Ah, didn't even think of that! thanks Fellas, and keep up the good work!
