### ISSUE TITLE
Hi, is there any way to scroll the song name (from right to left) and change its font? could u please show me via some link or video?

### ISSUE THREAD

**Issue by 1elvinn** [swiftcodex/Swift-Radio-Pro#75]

**Comment by swiftcodex** [comment]
Hi @1elvinn, There are many pre-built scroll label controls on Github that you can add to the code. For example:

- https://github.com/cbpowell/MarqueeLabel
- https://github.com/cbess/AutoScrollLabel
- etc

You can change fonts without modifying any code if you desire. You can simply select the label in Interface Builder and change the font in the right-hand menu. Look for the section that looks similar to this:

![screen shot 2017-11-04 at 5 02 22 pm](https://user-images.githubusercontent.com/2042313/32409439-1fdc9262-c182-11e7-9477-293dea5455f6.png)

**Comment by 1elvinn** [comment]
How can I solve this problem?
![error](https://user-images.githubusercontent.com/33378874/32459754-1c320dda-c34a-11e7-8e94-4622936dba52.png)
