### ISSUE TITLE
Local file and related play status supported.

### ISSUE THREAD

**Issue by aloveric** [swiftcodex/Swift-Radio-Pro#78]
Could you please add feature for progress/play/pause/next/previous of local files? Thanks.

**Comment by swiftcodex** [comment]
While this does not fit into the intended purpose of this app. There are many Tutorials online and in books on how to play back local files in Swift.

**Comment by swiftcodex** [comment]
Or, you could use a ready-made solution like this if you need something pre-built: https://github.com/AppliKeySolutions/PandoraPlayer

**Comment by aloveric** [comment]
Thanks @swiftcodex . I also find this project PandoraPlayer :)
