### ISSUE TITLE
Pull to Refresh Stations Doesn't Appear To Work.

### ISSUE THREAD

**Issue by thomaskloos** [swiftcodex/Swift-Radio-Pro#9]
Just to make sure, I downloaded the latest zip file yesterday, I added my URL to stations.json. It loads fine initially. Then I edited the file by removing a station and no matter how many times I pull down to refresh, it doesn't load the new file. Any ideas?

**Comment by swiftcodex** [comment]
I have just tested this feature on two different devices (iPhone 6s Plus and 5s) and it appears to work. I'm inclined to mark this issue as closed.

**Comment by thomaskloos** [comment]
how can I show you? I tried it on 4s, 5, and 6+
